# Tensor Operationen

## Tensoroperationen sind stark optimiert

In [1]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] = max(x[i, j], 0)
    return x

In [2]:
def naive_add(x, y):
    assert len(x.shape) == 2 
    assert x.shape == y.shape 
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] += y[i, j]
    return x

In [3]:
import numpy as np 

x = np.random.random((20, 100)) 
y = np.random.random((20, 100)) 



In [4]:
%timeit z = x + y

650 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%timeit z = naive_add(x, y)

342 µs ± 2.87 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
z = x + y
%timeit zz = np.maximum(z, 0.)

963 ns ± 6.51 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%timeit zz = naive_relu(z)

330 µs ± 456 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Broadcasting Beispiel

In [8]:
# Die Grundrechenarten und die Anwendung von Funktionen sind elementwise definiert
x = np.random.random((64, 3, 32, 10)) 
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [9]:
z.shape

(64, 3, 32, 10)

In [10]:
y

array([[2.79241605e-01, 6.63112440e-01, 7.21100620e-01, 4.48137515e-01,
        1.07964864e-03, 5.52536487e-01, 8.99336138e-01, 4.46693641e-01,
        1.36642024e-01, 6.34035087e-01],
       [7.34418015e-01, 9.75543884e-01, 4.80124234e-01, 5.60290228e-01,
        6.31018627e-01, 5.41109198e-01, 2.34877449e-01, 1.95082430e-01,
        2.28605312e-01, 3.31501697e-01],
       [5.84781763e-01, 2.06269638e-01, 5.75747231e-01, 6.28299782e-01,
        4.23520023e-01, 1.26483117e-01, 3.08064190e-01, 9.64734474e-01,
        9.56100419e-02, 6.20856595e-01],
       [1.47387915e-01, 1.22031242e-01, 8.40080916e-01, 2.14670577e-01,
        5.61163683e-01, 6.57558938e-01, 4.54324696e-01, 7.97978732e-01,
        5.90179146e-01, 7.42191942e-01],
       [2.70825038e-01, 6.02004798e-01, 2.91386025e-01, 1.88674734e-01,
        7.85257087e-01, 4.62233103e-01, 9.67463730e-01, 6.00906302e-01,
        5.87890881e-01, 8.69659612e-01],
       [4.19324593e-01, 8.79002143e-01, 9.49539741e-01, 5.39873295e-01,
   

# Dot Produkt

In [11]:
x = np.random.random((32)) 
y = np.random.random((32)) 
z = np.dot(x, y)

In [12]:
z.shape

()

In [13]:
x = np.random.random((1,32)) 
y = np.random.random((32,1)) 
z = np.dot(x, y)

In [14]:
z

array([[6.94961635]])

In [15]:
# VORSICHT! MANCHE MENSCHEN MEINEN DOT-PRODUKT SOLLTE AUCH BEI MATRIZEN SKALAREN OUTPUT HABEN
x = np.random.random((32,5)) 
y = np.random.random((5,32)) 
z = np.dot(x, y)

In [16]:
z.shape

(32, 32)

In [17]:
x = np.random.random((9,3,4,8))
y = np.random.random((8,2)) # aber (8,2,3) geht nicht.

z = np.dot(x,y)
z.shape

(9, 3, 4, 2)

In [18]:
x = np.array([1,2,3]) 
x.shape

(3,)

In [19]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1 
    assert len(y.shape) == 1 
    assert x.shape[0] == y.shape[0] 
    
    z = 0.
    for i in range(x.shape[0]): 
        z += x[i] * y[i]
    return z

In [20]:
def naive_matrix_vector_dot(x, y): 
    assert len(x.shape) == 2 
    assert len(y.shape) == 1 
    assert x.shape[1] == y.shape[0] 
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]): 
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

# Übung
* Benchmarken der beiden naiven "vector_dot"-Implementierungen vs Numpy
* Wie ändert sich die Runtime mit der Dimensionalität des Inputs?

In [21]:
x = np.random.random((8))
y = np.random.random((8)) # aber (8,2,3) geht nicht.
len(x.shape)
x

array([0.14933739, 0.97839583, 0.70210124, 0.42166439, 0.36462622,
       0.97524218, 0.17871937, 0.98521216])

In [22]:
%timeit z = naive_vector_dot(x, y)

1.33 µs ± 9.33 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
%timeit z = np.dot(x,y)

433 ns ± 3.28 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Tensor Reshaping

In [24]:
x = np.array([[0., 1.], 
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [25]:
x = x.reshape((6, 1))

In [26]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [27]:
x = x.reshape((2,3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [28]:
x = x.reshape((3,2))
x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [29]:
# Aber: transponieren ändert die Reihenfolge
x = x.transpose()
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [30]:
x = x.reshape((3,2))
x

array([[0., 2.],
       [4., 1.],
       [3., 5.]])