# Einführung tensorflow/numpy
Dieses Notebook gibt eine kleine Einführung in die packages tensorflow und numpy

## Imports

In [1]:
import tensorflow as tf
import numpy as np

## numpy

In [2]:
a = np.array([[2,4,5],[5,6,7]], dtype="int")  # mit dtype Zuweisung

In [3]:
a

array([[2, 4, 5],
       [5, 6, 7]])

In [4]:
a[:,:]

array([[2, 4, 5],
       [5, 6, 7]])

In [5]:
type(a)

numpy.ndarray

### Umwandlung von tf Tensor zu numpy Array

In [6]:
tensor = tf.constant(a)

In [7]:
type(tensor.numpy())

numpy.ndarray

In [8]:
np.square(tensor.numpy())

array([[ 4, 16, 25],
       [25, 36, 49]])

## tensorflow

### Das Tensorformat

Erstellen eines Tensors mit `tf.constant`

In [9]:
m = tf.constant([[1,2,3],[4,5,6]]) # Rank2

Sowohl shape (2 rows, 3 columns), numpy Representation also auch der Datentyp werden angezeigt

In [10]:
print(m) 

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Skalar (Rank 0)

In [11]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Abfragen der Shape

In [12]:
m.shape

TensorShape([2, 3])

Der Datentyp ist wichtig, da alles Einträge den gleichen Datentyp haben müssen

In [13]:
m.dtype

tf.int32

Indexing

In [14]:
m[:, 0]  # Alle Zeilen Spalte 0

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [15]:
m[1,:]  # Zweite Zeile alle Spalten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

### Rechenoperationen

In [16]:
t= tf.constant([[1,2,3],[4,5,6]])
print(t)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Summe 

In [17]:
print(t + 10)
# Ist das gleiche wie:
print(tf.add(t, 10))

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


Quadrieren

In [18]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [19]:
np.sum()

TypeError: sum() missing 1 required positional argument: 'a'

Matrix Multiplikation mit transponierter Matrix

In [20]:
print(t)
print(tf.transpose(t))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [21]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

### Type conversion

In [22]:
c = tf.constant([[10,5,1],[3,7,11]])


Folgende Zeile gibt einen Fehler aus

In [23]:
c + 1.0

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [24]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  5,  1],
       [ 3,  7, 11]], dtype=int32)>

Um die Summe eines int Typ Tensors und eines floats berechnen zu können, ist es nötig den Tensor erst als float Typ zu casten.

In [25]:
tf.cast(c,tf.float32) + 1.0

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11.,  6.,  2.],
       [ 4.,  8., 12.]], dtype=float32)>

#### Wichtig: Tensoren mit `tf.constant` sind immutable. Das heißt sie können nicht verändert werden. Stattdessen benötift man eine `tf.Variable` (z.B für Custom Metriken oder Weights in Neuronalen Netzen)

In [26]:
v = tf.Variable(5)
v.assign(2*v)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
